// src/app/layout.tsx

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* The dedicated, fixed background element */}
        <div className="bg-gradient-container" />

        {/* 
          A content wrapper that sits on top of the background.
          'relative' and 'isolate' create a new stacking context, 
          ensuring content doesn't accidentally appear behind the background.
        */}
        <div className="relative isolate min-h-screen">{children}</div>
      </body>
    </html>
  );
}
